sonar.projectName=pssg-cscp-cpu

# Path to sources
sonar.sources=Database,Manager.Contract,Manager,Resources,Shared.Contract,Shared.Database,cpu-app,cpu-interfaces
#sonar.exclusions=
#sonar.inclusions=

# Path to tests
sonar.tests=Tests
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=