/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  DocumentCollectionResponseDto,
  DownloadDocumentDto,
  FilePost,
  SignedContractPostFromPortal,
  UploadResponseDto
} from '../../models';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class FileService {
  private readonly http = inject(HttpClient);
 getApiFileBusinessBceidUserBceidDocumentsContractContractId<TData = DocumentCollectionResponseDto>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiFileBusinessBceidUserBceidDocumentsContractContractId<TData = DocumentCollectionResponseDto>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiFileBusinessBceidUserBceidDocumentsContractContractId<TData = DocumentCollectionResponseDto>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiFileBusinessBceidUserBceidDocumentsContractContractId<TData = DocumentCollectionResponseDto>(
    businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/File/${businessBceid}/${userBceid}/documents/contract/${contractId}`,options
    );
  }
 getApiFileBusinessBceidUserBceidDocumentsAccountAccountId<TData = DocumentCollectionResponseDto>(businessBceid: string,
    userBceid: string,
    accountId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiFileBusinessBceidUserBceidDocumentsAccountAccountId<TData = DocumentCollectionResponseDto>(businessBceid: string,
    userBceid: string,
    accountId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiFileBusinessBceidUserBceidDocumentsAccountAccountId<TData = DocumentCollectionResponseDto>(businessBceid: string,
    userBceid: string,
    accountId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiFileBusinessBceidUserBceidDocumentsAccountAccountId<TData = DocumentCollectionResponseDto>(
    businessBceid: string,
    userBceid: string,
    accountId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/File/${businessBceid}/${userBceid}/documents/account/${accountId}`,options
    );
  }
 getApiFileBusinessBceidUserBceidDocumentDocId<TData = DownloadDocumentDto>(businessBceid: string,
    userBceid: string,
    docId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiFileBusinessBceidUserBceidDocumentDocId<TData = DownloadDocumentDto>(businessBceid: string,
    userBceid: string,
    docId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiFileBusinessBceidUserBceidDocumentDocId<TData = DownloadDocumentDto>(businessBceid: string,
    userBceid: string,
    docId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiFileBusinessBceidUserBceidDocumentDocId<TData = DownloadDocumentDto>(
    businessBceid: string,
    userBceid: string,
    docId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/File/${businessBceid}/${userBceid}/document/${docId}`,options
    );
  }
 getApiFileContractPackageBusinessBceidUserBceidTaskId<TData = DocumentCollectionResponseDto>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiFileContractPackageBusinessBceidUserBceidTaskId<TData = DocumentCollectionResponseDto>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiFileContractPackageBusinessBceidUserBceidTaskId<TData = DocumentCollectionResponseDto>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiFileContractPackageBusinessBceidUserBceidTaskId<TData = DocumentCollectionResponseDto>(
    businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/File/contract_package/${businessBceid}/${userBceid}/${taskId}`,options
    );
  }
 postApiFileSignedContractTaskId<TData = UploadResponseDto>(taskId: string,
    signedContractPostFromPortal: SignedContractPostFromPortal, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiFileSignedContractTaskId<TData = UploadResponseDto>(taskId: string,
    signedContractPostFromPortal: SignedContractPostFromPortal, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiFileSignedContractTaskId<TData = UploadResponseDto>(taskId: string,
    signedContractPostFromPortal: SignedContractPostFromPortal, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiFileSignedContractTaskId<TData = UploadResponseDto>(
    taskId: string,
    signedContractPostFromPortal: SignedContractPostFromPortal, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/File/signed_contract/${taskId}`,
      signedContractPostFromPortal,options
    );
  }
 postApiFileAccountAccountId<TData = UploadResponseDto>(accountId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiFileAccountAccountId<TData = UploadResponseDto>(accountId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiFileAccountAccountId<TData = UploadResponseDto>(accountId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiFileAccountAccountId<TData = UploadResponseDto>(
    accountId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/File/account/${accountId}`,
      filePost,options
    );
  }
 postApiFileContractContractId<TData = UploadResponseDto>(contractId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiFileContractContractId<TData = UploadResponseDto>(contractId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiFileContractContractId<TData = UploadResponseDto>(contractId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiFileContractContractId<TData = UploadResponseDto>(
    contractId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/File/contract/${contractId}`,
      filePost,options
    );
  }
};

export type GetApiFileBusinessBceidUserBceidDocumentsContractContractIdClientResult = NonNullable<DocumentCollectionResponseDto>
export type GetApiFileBusinessBceidUserBceidDocumentsAccountAccountIdClientResult = NonNullable<DocumentCollectionResponseDto>
export type GetApiFileBusinessBceidUserBceidDocumentDocIdClientResult = NonNullable<DownloadDocumentDto>
export type GetApiFileContractPackageBusinessBceidUserBceidTaskIdClientResult = NonNullable<DocumentCollectionResponseDto>
export type PostApiFileSignedContractTaskIdClientResult = NonNullable<UploadResponseDto>
export type PostApiFileAccountAccountIdClientResult = NonNullable<UploadResponseDto>
export type PostApiFileContractContractIdClientResult = NonNullable<UploadResponseDto>
