/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  MonthlyStatisticsAnswers
} from '../../models';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class DynamicsStatusReportService {
  private readonly http = inject(HttpClient);
 getApiDynamicsStatusReportBusinessBceidUserBceidTaskId<TData = void>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiDynamicsStatusReportBusinessBceidUserBceidTaskId<TData = void>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiDynamicsStatusReportBusinessBceidUserBceidTaskId<TData = void>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiDynamicsStatusReportBusinessBceidUserBceidTaskId<TData = void>(
    businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/DynamicsStatusReport/${businessBceid}/${userBceid}/${taskId}`,options
    );
  }
 getApiDynamicsStatusReportMonthlyStatsBusinessBceidUserBceidContractId<TData = void>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiDynamicsStatusReportMonthlyStatsBusinessBceidUserBceidContractId<TData = void>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiDynamicsStatusReportMonthlyStatsBusinessBceidUserBceidContractId<TData = void>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiDynamicsStatusReportMonthlyStatsBusinessBceidUserBceidContractId<TData = void>(
    businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/DynamicsStatusReport/monthly_stats/${businessBceid}/${userBceid}/${contractId}`,options
    );
  }
 getApiDynamicsStatusReportDataCollectionBusinessBceidUserBceidDataCollectionId<TData = void>(businessBceid: string,
    userBceid: string,
    dataCollectionId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiDynamicsStatusReportDataCollectionBusinessBceidUserBceidDataCollectionId<TData = void>(businessBceid: string,
    userBceid: string,
    dataCollectionId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiDynamicsStatusReportDataCollectionBusinessBceidUserBceidDataCollectionId<TData = void>(businessBceid: string,
    userBceid: string,
    dataCollectionId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiDynamicsStatusReportDataCollectionBusinessBceidUserBceidDataCollectionId<TData = void>(
    businessBceid: string,
    userBceid: string,
    dataCollectionId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/DynamicsStatusReport/data_collection/${businessBceid}/${userBceid}/${dataCollectionId}`,options
    );
  }
 postApiDynamicsStatusReportTaskId<TData = void>(taskId: string,
    monthlyStatisticsAnswers: MonthlyStatisticsAnswers, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiDynamicsStatusReportTaskId<TData = void>(taskId: string,
    monthlyStatisticsAnswers: MonthlyStatisticsAnswers, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiDynamicsStatusReportTaskId<TData = void>(taskId: string,
    monthlyStatisticsAnswers: MonthlyStatisticsAnswers, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiDynamicsStatusReportTaskId<TData = void>(
    taskId: string,
    monthlyStatisticsAnswers: MonthlyStatisticsAnswers, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/DynamicsStatusReport/${taskId}`,
      monthlyStatisticsAnswers,options
    );
  }
 getApiDynamicsStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramName<TData = void>(contractId: string,
    programId: string,
    contractNumber: string,
    programName: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiDynamicsStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramName<TData = void>(contractId: string,
    programId: string,
    contractNumber: string,
    programName: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiDynamicsStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramName<TData = void>(contractId: string,
    programId: string,
    contractNumber: string,
    programName: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiDynamicsStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramName<TData = void>(
    contractId: string,
    programId: string,
    contractNumber: string,
    programName: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/DynamicsStatusReport/export_monthly_report/${contractId}/${programId}/${contractNumber}/${programName}`,options
    );
  }
};

export type GetApiDynamicsStatusReportBusinessBceidUserBceidTaskIdClientResult = NonNullable<void>
export type GetApiDynamicsStatusReportMonthlyStatsBusinessBceidUserBceidContractIdClientResult = NonNullable<void>
export type GetApiDynamicsStatusReportDataCollectionBusinessBceidUserBceidDataCollectionIdClientResult = NonNullable<void>
export type PostApiDynamicsStatusReportTaskIdClientResult = NonNullable<void>
export type GetApiDynamicsStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramNameClientResult = NonNullable<void>
