/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  FilePost,
  SignedContractPostFromPortal
} from '../../models';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class DynamicsFileService {
  private readonly http = inject(HttpClient);
 getApiDynamicsFileBusinessBceidUserBceidDocumentsContractContractId<TData = void>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiDynamicsFileBusinessBceidUserBceidDocumentsContractContractId<TData = void>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiDynamicsFileBusinessBceidUserBceidDocumentsContractContractId<TData = void>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiDynamicsFileBusinessBceidUserBceidDocumentsContractContractId<TData = void>(
    businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/DynamicsFile/${businessBceid}/${userBceid}/documents/contract/${contractId}`,options
    );
  }
 getApiDynamicsFileBusinessBceidUserBceidDocumentsAccountAccountId<TData = void>(businessBceid: string,
    userBceid: string,
    accountId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiDynamicsFileBusinessBceidUserBceidDocumentsAccountAccountId<TData = void>(businessBceid: string,
    userBceid: string,
    accountId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiDynamicsFileBusinessBceidUserBceidDocumentsAccountAccountId<TData = void>(businessBceid: string,
    userBceid: string,
    accountId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiDynamicsFileBusinessBceidUserBceidDocumentsAccountAccountId<TData = void>(
    businessBceid: string,
    userBceid: string,
    accountId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/DynamicsFile/${businessBceid}/${userBceid}/documents/account/${accountId}`,options
    );
  }
 getApiDynamicsFileBusinessBceidUserBceidDocumentDocId<TData = void>(businessBceid: string,
    userBceid: string,
    docId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiDynamicsFileBusinessBceidUserBceidDocumentDocId<TData = void>(businessBceid: string,
    userBceid: string,
    docId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiDynamicsFileBusinessBceidUserBceidDocumentDocId<TData = void>(businessBceid: string,
    userBceid: string,
    docId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiDynamicsFileBusinessBceidUserBceidDocumentDocId<TData = void>(
    businessBceid: string,
    userBceid: string,
    docId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/DynamicsFile/${businessBceid}/${userBceid}/document/${docId}`,options
    );
  }
 getApiDynamicsFileContractPackageBusinessBceidUserBceidTaskId<TData = void>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiDynamicsFileContractPackageBusinessBceidUserBceidTaskId<TData = void>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiDynamicsFileContractPackageBusinessBceidUserBceidTaskId<TData = void>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiDynamicsFileContractPackageBusinessBceidUserBceidTaskId<TData = void>(
    businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/DynamicsFile/contract_package/${businessBceid}/${userBceid}/${taskId}`,options
    );
  }
 postApiDynamicsFileSignedContractTaskId<TData = void>(taskId: string,
    signedContractPostFromPortal: SignedContractPostFromPortal, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiDynamicsFileSignedContractTaskId<TData = void>(taskId: string,
    signedContractPostFromPortal: SignedContractPostFromPortal, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiDynamicsFileSignedContractTaskId<TData = void>(taskId: string,
    signedContractPostFromPortal: SignedContractPostFromPortal, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiDynamicsFileSignedContractTaskId<TData = void>(
    taskId: string,
    signedContractPostFromPortal: SignedContractPostFromPortal, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/DynamicsFile/signed_contract/${taskId}`,
      signedContractPostFromPortal,options
    );
  }
 postApiDynamicsFileAccountAccountId<TData = void>(accountId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiDynamicsFileAccountAccountId<TData = void>(accountId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiDynamicsFileAccountAccountId<TData = void>(accountId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiDynamicsFileAccountAccountId<TData = void>(
    accountId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/DynamicsFile/account/${accountId}`,
      filePost,options
    );
  }
 postApiDynamicsFileContractContractId<TData = void>(contractId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiDynamicsFileContractContractId<TData = void>(contractId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiDynamicsFileContractContractId<TData = void>(contractId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiDynamicsFileContractContractId<TData = void>(
    contractId: string,
    filePost: FilePost, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/DynamicsFile/contract/${contractId}`,
      filePost,options
    );
  }
};

export type GetApiDynamicsFileBusinessBceidUserBceidDocumentsContractContractIdClientResult = NonNullable<void>
export type GetApiDynamicsFileBusinessBceidUserBceidDocumentsAccountAccountIdClientResult = NonNullable<void>
export type GetApiDynamicsFileBusinessBceidUserBceidDocumentDocIdClientResult = NonNullable<void>
export type GetApiDynamicsFileContractPackageBusinessBceidUserBceidTaskIdClientResult = NonNullable<void>
export type PostApiDynamicsFileSignedContractTaskIdClientResult = NonNullable<void>
export type PostApiDynamicsFileAccountAccountIdClientResult = NonNullable<void>
export type PostApiDynamicsFileContractContractIdClientResult = NonNullable<void>
