/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ExpenseReportDto,
  ExpenseReportPost
} from '../../models';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class ExpenseReportService {
  private readonly http = inject(HttpClient);
 getApiExpenseReportBusinessBceidUserBceidExpenseReportId<TData = ExpenseReportDto>(businessBceid: string,
    userBceid: string,
    expenseReportId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiExpenseReportBusinessBceidUserBceidExpenseReportId<TData = ExpenseReportDto>(businessBceid: string,
    userBceid: string,
    expenseReportId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiExpenseReportBusinessBceidUserBceidExpenseReportId<TData = ExpenseReportDto>(businessBceid: string,
    userBceid: string,
    expenseReportId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiExpenseReportBusinessBceidUserBceidExpenseReportId<TData = ExpenseReportDto>(
    businessBceid: string,
    userBceid: string,
    expenseReportId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/coastcontracts/api/ExpenseReport/${businessBceid}/${userBceid}/${expenseReportId}`,options
    );
  }
 postApiExpenseReport<TData = void>(expenseReportPost: ExpenseReportPost, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiExpenseReport<TData = void>(expenseReportPost: ExpenseReportPost, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiExpenseReport<TData = void>(expenseReportPost: ExpenseReportPost, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiExpenseReport<TData = void>(
    expenseReportPost: ExpenseReportPost, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/coastcontracts/api/ExpenseReport`,
      expenseReportPost,options
    );
  }
};

export type GetApiExpenseReportBusinessBceidUserBceidExpenseReportIdClientResult = NonNullable<ExpenseReportDto>
export type PostApiExpenseReportClientResult = NonNullable<void>
