/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ProgramSurplusPost
} from '../../models';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class DynamicsProgramSurplusService {
  private readonly http = inject(HttpClient);
 getApiDynamicsProgramSurplusBusinessBceidUserBceidSurplusId<TData = void>(businessBceid: string,
    userBceid: string,
    surplusId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiDynamicsProgramSurplusBusinessBceidUserBceidSurplusId<TData = void>(businessBceid: string,
    userBceid: string,
    surplusId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiDynamicsProgramSurplusBusinessBceidUserBceidSurplusId<TData = void>(businessBceid: string,
    userBceid: string,
    surplusId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiDynamicsProgramSurplusBusinessBceidUserBceidSurplusId<TData = void>(
    businessBceid: string,
    userBceid: string,
    surplusId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/DynamicsProgramSurplus/${businessBceid}/${userBceid}/${surplusId}`,options
    );
  }
 postApiDynamicsProgramSurplus<TData = void>(programSurplusPost: ProgramSurplusPost, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiDynamicsProgramSurplus<TData = void>(programSurplusPost: ProgramSurplusPost, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiDynamicsProgramSurplus<TData = void>(programSurplusPost: ProgramSurplusPost, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiDynamicsProgramSurplus<TData = void>(
    programSurplusPost: ProgramSurplusPost, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/DynamicsProgramSurplus`,
      programSurplusPost,options
    );
  }
};

export type GetApiDynamicsProgramSurplusBusinessBceidUserBceidSurplusIdClientResult = NonNullable<void>
export type PostApiDynamicsProgramSurplusClientResult = NonNullable<void>
