/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  MonthlyStatisticsAnswers,
  MonthlyStatisticsDto,
  SetStatusReportAnswersResponseDto,
  StatusReportAnswersDto,
  StatusReportQuestionsDto
} from '../../models';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class StatusReportService {
  private readonly http = inject(HttpClient);
 getApiStatusReportBusinessBceidUserBceidTaskId<TData = StatusReportQuestionsDto>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiStatusReportBusinessBceidUserBceidTaskId<TData = StatusReportQuestionsDto>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiStatusReportBusinessBceidUserBceidTaskId<TData = StatusReportQuestionsDto>(businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiStatusReportBusinessBceidUserBceidTaskId<TData = StatusReportQuestionsDto>(
    businessBceid: string,
    userBceid: string,
    taskId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/coastcontracts/api/StatusReport/${businessBceid}/${userBceid}/${taskId}`,options
    );
  }
 getApiStatusReportMonthlyStatsBusinessBceidUserBceidContractId<TData = MonthlyStatisticsDto>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiStatusReportMonthlyStatsBusinessBceidUserBceidContractId<TData = MonthlyStatisticsDto>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiStatusReportMonthlyStatsBusinessBceidUserBceidContractId<TData = MonthlyStatisticsDto>(businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiStatusReportMonthlyStatsBusinessBceidUserBceidContractId<TData = MonthlyStatisticsDto>(
    businessBceid: string,
    userBceid: string,
    contractId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/coastcontracts/api/StatusReport/monthly_stats/${businessBceid}/${userBceid}/${contractId}`,options
    );
  }
 getApiStatusReportDataCollectionBusinessBceidUserBceidDataCollectionId<TData = StatusReportAnswersDto>(businessBceid: string,
    userBceid: string,
    dataCollectionId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiStatusReportDataCollectionBusinessBceidUserBceidDataCollectionId<TData = StatusReportAnswersDto>(businessBceid: string,
    userBceid: string,
    dataCollectionId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiStatusReportDataCollectionBusinessBceidUserBceidDataCollectionId<TData = StatusReportAnswersDto>(businessBceid: string,
    userBceid: string,
    dataCollectionId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiStatusReportDataCollectionBusinessBceidUserBceidDataCollectionId<TData = StatusReportAnswersDto>(
    businessBceid: string,
    userBceid: string,
    dataCollectionId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/coastcontracts/api/StatusReport/data_collection/${businessBceid}/${userBceid}/${dataCollectionId}`,options
    );
  }
 postApiStatusReportTaskId<TData = SetStatusReportAnswersResponseDto>(taskId: string,
    monthlyStatisticsAnswers: MonthlyStatisticsAnswers, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiStatusReportTaskId<TData = SetStatusReportAnswersResponseDto>(taskId: string,
    monthlyStatisticsAnswers: MonthlyStatisticsAnswers, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiStatusReportTaskId<TData = SetStatusReportAnswersResponseDto>(taskId: string,
    monthlyStatisticsAnswers: MonthlyStatisticsAnswers, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiStatusReportTaskId<TData = SetStatusReportAnswersResponseDto>(
    taskId: string,
    monthlyStatisticsAnswers: MonthlyStatisticsAnswers, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/coastcontracts/api/StatusReport/${taskId}`,
      monthlyStatisticsAnswers,options
    );
  }
 getApiStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramName<TData = void | void>(contractId: string,
    programId: string,
    contractNumber: string,
    programName: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramName<TData = void | void>(contractId: string,
    programId: string,
    contractNumber: string,
    programName: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramName<TData = void | void>(contractId: string,
    programId: string,
    contractNumber: string,
    programName: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramName<TData = void | void>(
    contractId: string,
    programId: string,
    contractNumber: string,
    programName: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/coastcontracts/api/StatusReport/export_monthly_report/${contractId}/${programId}/${contractNumber}/${programName}`,options
    );
  }
};

export type GetApiStatusReportBusinessBceidUserBceidTaskIdClientResult = NonNullable<StatusReportQuestionsDto>
export type GetApiStatusReportMonthlyStatsBusinessBceidUserBceidContractIdClientResult = NonNullable<MonthlyStatisticsDto>
export type GetApiStatusReportDataCollectionBusinessBceidUserBceidDataCollectionIdClientResult = NonNullable<StatusReportAnswersDto>
export type PostApiStatusReportTaskIdClientResult = NonNullable<SetStatusReportAnswersResponseDto>
export type GetApiStatusReportExportMonthlyReportContractIdProgramIdContractNumberProgramNameClientResult = NonNullable<void | void>
