/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  RegisterNewUserPost,
  SetOrgContractsResponseDto
} from '../../models';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class RegisterNewUserService {
  private readonly http = inject(HttpClient);
 postApiRegisterNewUser<TData = SetOrgContractsResponseDto>(registerNewUserPost: RegisterNewUserPost, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiRegisterNewUser<TData = SetOrgContractsResponseDto>(registerNewUserPost: RegisterNewUserPost, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiRegisterNewUser<TData = SetOrgContractsResponseDto>(registerNewUserPost: RegisterNewUserPost, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiRegisterNewUser<TData = SetOrgContractsResponseDto>(
    registerNewUserPost: RegisterNewUserPost, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/coastcontracts/api/RegisterNewUser`,
      registerNewUserPost,options
    );
  }
};

export type PostApiRegisterNewUserClientResult = NonNullable<SetOrgContractsResponseDto>
