/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class UserService {
  private readonly http = inject(HttpClient);
 getApiUserIsLoggedIn<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiUserIsLoggedIn<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiUserIsLoggedIn<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiUserIsLoggedIn<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/coastcontracts/api/User/isLoggedIn`,options
    );
  }
 getApiUserCurrent<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiUserCurrent<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiUserCurrent<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiUserCurrent<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/coastcontracts/api/User/current`,options
    );
  }
 getApiUserGetLogoutUrl<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiUserGetLogoutUrl<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiUserGetLogoutUrl<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiUserGetLogoutUrl<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/coastcontracts/api/User/GetLogoutUrl`,options
    );
  }
};

export type GetApiUserIsLoggedInClientResult = NonNullable<void>
export type GetApiUserCurrentClientResult = NonNullable<void>
export type GetApiUserGetLogoutUrlClientResult = NonNullable<void>
