/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  ProgramApplicationDto,
  ProgramApplicationPost
} from '../../models';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class ProgramApplicationService {
  private readonly http = inject(HttpClient);
 getApiProgramApplicationBusinessBceidUserBceidScheduleFId<TData = ProgramApplicationDto>(businessBceid: string,
    userBceid: string,
    scheduleFId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getApiProgramApplicationBusinessBceidUserBceidScheduleFId<TData = ProgramApplicationDto>(businessBceid: string,
    userBceid: string,
    scheduleFId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getApiProgramApplicationBusinessBceidUserBceidScheduleFId<TData = ProgramApplicationDto>(businessBceid: string,
    userBceid: string,
    scheduleFId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getApiProgramApplicationBusinessBceidUserBceidScheduleFId<TData = ProgramApplicationDto>(
    businessBceid: string,
    userBceid: string,
    scheduleFId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/api/ProgramApplication/${businessBceid}/${userBceid}/${scheduleFId}`,options
    );
  }
 postApiProgramApplication<TData = void>(programApplicationPost: ProgramApplicationPost, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postApiProgramApplication<TData = void>(programApplicationPost: ProgramApplicationPost, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postApiProgramApplication<TData = void>(programApplicationPost: ProgramApplicationPost, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postApiProgramApplication<TData = void>(
    programApplicationPost: ProgramApplicationPost, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/api/ProgramApplication`,
      programApplicationPost,options
    );
  }
};

export type GetApiProgramApplicationBusinessBceidUserBceidScheduleFIdClientResult = NonNullable<ProgramApplicationDto>
export type PostApiProgramApplicationClientResult = NonNullable<void>
