/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsBudgetProposalExpensePost } from './dynamicsBudgetProposalExpensePost';
import type { DynamicsBudgetProposalRevenueSourcePost } from './dynamicsBudgetProposalRevenueSourcePost';
import type { DynamicsBudgetProposalProgramPost } from './dynamicsBudgetProposalProgramPost';

export interface BudgetProposalPost {
  /** @minLength 1 */
  businessBCeID: string;
  /** @minLength 1 */
  userBCeID: string;
  programExpenseCollection: DynamicsBudgetProposalExpensePost[];
  programRevenueSourceCollection: DynamicsBudgetProposalRevenueSourcePost[];
  /** @minItems 1 */
  programCollection: DynamicsBudgetProposalProgramPost[];
}
