/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsBudgetProposalExpensePost } from './dynamicsBudgetProposalExpensePost';
import type { DynamicsBudgetProposalRevenueSourcePost } from './dynamicsBudgetProposalRevenueSourcePost';
import type { DynamicsBudgetProposalProgramPost } from './dynamicsBudgetProposalProgramPost';

export interface BudgetProposalPost {
  /** @nullable */
  businessBCeID?: string | null;
  /** @nullable */
  userBCeID?: string | null;
  /** @nullable */
  programExpenseCollection?: DynamicsBudgetProposalExpensePost[] | null;
  /** @nullable */
  programRevenueSourceCollection?: DynamicsBudgetProposalRevenueSourcePost[] | null;
  /** @nullable */
  programCollection?: DynamicsBudgetProposalProgramPost[] | null;
}
