/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsCAPApplicationContractPost } from './dynamicsCAPApplicationContractPost';
import type { DynamicsCAPApplicationOrganizationPost } from './dynamicsCAPApplicationOrganizationPost';
import type { DynamicsCAPApplicationProgramContactPost } from './dynamicsCAPApplicationProgramContactPost';
import type { DynamicsCAPApplicationProgramPost } from './dynamicsCAPApplicationProgramPost';

export interface CAPApplicationPost {
  /** @minLength 1 */
  businessBCeID: string;
  /** @minLength 1 */
  userBCeID: string;
  /** @minItems 1 */
  contractCollection: DynamicsCAPApplicationContractPost[];
  organization: DynamicsCAPApplicationOrganizationPost;
  /** @nullable */
  addProgramContactCollection?: DynamicsCAPApplicationProgramContactPost[] | null;
  /** @nullable */
  removeProgramContactCollection?: DynamicsCAPApplicationProgramContactPost[] | null;
  /** @minItems 1 */
  programCollection: DynamicsCAPApplicationProgramPost[];
}
