/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { ContactDto } from './contactDto';
import type { ContractDto } from './contractDto';
import type { OrganizationDto } from './organizationDto';
import type { PortalRoleDto } from './portalRoleDto';
import type { ProgramDto } from './programDto';
import type { ProgramContactDto } from './programContactDto';
import type { ProgramTypeDto } from './programTypeDto';

export interface CAPApplicationDto {
  boardContact?: ContactDto;
  /** @nullable */
  businessbceid?: string | null;
  contract?: ContractDto;
  executiveContact?: ContactDto;
  isSuccess?: boolean;
  organization?: OrganizationDto;
  /** @nullable */
  portalRoles?: PortalRoleDto[] | null;
  /** @nullable */
  programCollection?: ProgramDto[] | null;
  /** @nullable */
  programContactCollection?: ProgramContactDto[] | null;
  programManager?: ContactDto;
  /** @nullable */
  programTypeCollection?: ProgramTypeDto[] | null;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  staffCollection?: ContactDto[] | null;
  /** @nullable */
  userbceid?: string | null;
}
