/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface ContactDto {
  /** @nullable */
  contactId?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  middleName?: string | null;
  /** @nullable */
  emailAddress1?: string | null;
  /** @nullable */
  mobilePhone?: string | null;
  /** @nullable */
  fax?: string | null;
  /** @nullable */
  jobTitle?: string | null;
  /** @nullable */
  address1City?: string | null;
  /** @nullable */
  address1Line1?: string | null;
  /** @nullable */
  address1Line2?: string | null;
  /** @nullable */
  address1PostalCode?: string | null;
  /** @nullable */
  address1StateOrProvince?: string | null;
  /** @nullable */
  vsd_BceId?: string | null;
  /** @nullable */
  vsd_MainPhoneExtension?: string | null;
  /** @nullable */
  telephone2?: string | null;
  /** @nullable */
  vsd_HomePhoneExtension?: string | null;
  /** @nullable */
  vsd_EmploymentStatus?: number | null;
  /** @nullable */
  stateCode?: number | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
