/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface ContactMinimalDto {
  /** @nullable */
  contactid?: string | null;
  /** @nullable */
  fullname?: string | null;
}
