/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface ContractDto {
  /** @nullable */
  vsd_ContractId?: string | null;
  /** @nullable */
  vsd_Name?: string | null;
  /** @nullable */
  vsd_FiscalStartDate?: string | null;
  /** @nullable */
  statusCode?: number | null;
  /** @nullable */
  vsd_ContactLookup1IdValue?: string | null;
  /** @nullable */
  vsd_ContactLookup2IdValue?: string | null;
  /** @nullable */
  vsd_Cpu_InsuranceOptions?: number | null;
  /** @nullable */
  vsd_Cpu_MemberOfCssea?: number | null;
  /** @nullable */
  vsd_Cpu_HumanResourcePolices?: string | null;
  /** @nullable */
  vsd_Cpu_SpecificUnion?: string | null;
  /** @nullable */
  vsd_Cpu_SubcontractedProgramStaff?: number | null;
  /** @nullable */
  vsd_Cpu_UnionizedStaff?: number | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
