/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { ContactDto } from './contactDto';
import type { ContractDto } from './contractDto';
import type { InvoiceDto } from './invoiceDto';
import type { MessageDto } from './messageDto';
import type { SystemUserDto } from './systemUserDto';
import type { OrganizationDto } from './organizationDto';
import type { PortalRoleDto } from './portalRoleDto';
import type { ProgramDto } from './programDto';
import type { TaskDto } from './taskDto';

export interface CpuOrgContractsDto {
  boardContact?: ContactDto;
  /** @nullable */
  businessbceid?: string | null;
  /** @nullable */
  contracts?: ContractDto[] | null;
  executiveContact?: ContactDto;
  /** @nullable */
  invoices?: InvoiceDto[] | null;
  isSuccess?: boolean;
  /** @nullable */
  messages?: MessageDto[] | null;
  ministryUser?: SystemUserDto;
  organization?: OrganizationDto;
  /** @nullable */
  portalRoles?: PortalRoleDto[] | null;
  /** @nullable */
  programs?: ProgramDto[] | null;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  staff?: ContactDto[] | null;
  /** @nullable */
  tasks?: TaskDto[] | null;
  /** @nullable */
  userbceid?: string | null;
  /** @nullable */
  fortunecookiecontext?: string | null;
}
