/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DataCollectionItemDto {
  /** @nullable */
  vsd_datacollectionid?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  vsd_reportingperiod?: number | null;
  /** @nullable */
  statuscode?: number | null;
  /** @nullable */
  vsd_submissiondate?: string | null;
  /** @nullable */
  _vsd_contact_value?: string | null;
  /** @nullable */
  createdon?: string | null;
  /** @nullable */
  _vsd_program_value?: string | null;
}
