/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DocumentItemDto } from './documentItemDto';

export interface DocumentCollectionResponseDto {
  isSuccess?: boolean;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  businessbceid?: string | null;
  /** @nullable */
  userbceid?: string | null;
  /** @nullable */
  documentCollection?: DocumentItemDto[] | null;
}
