/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DownloadDocumentDto {
  isSuccess?: boolean;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  fileSize?: number | null;
  /** @nullable */
  mimeType?: string | null;
  /** @nullable */
  receivedDate?: string | null;
}
