/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsOrganizationPost {
  /** @nullable */
  _ownerid_value?: string | null;
  /** @nullable */
  vsd_ExecutiveContactIdfortunecookiebind?: string | null;
  /** @nullable */
  vsd_BoardContactIdfortunecookiebind?: string | null;
  /** @nullable */
  accountid?: string | null;
  /** @nullable */
  address1_city?: string | null;
  /** @nullable */
  address1_composite?: string | null;
  /** @nullable */
  address1_line1?: string | null;
  /** @nullable */
  address1_line2?: string | null;
  /** @nullable */
  address1_postalcode?: string | null;
  /** @nullable */
  address1_stateorprovince?: string | null;
  /** @nullable */
  address2_city?: string | null;
  /** @nullable */
  address2_composite?: string | null;
  /** @nullable */
  address2_line1?: string | null;
  /** @nullable */
  address2_line2?: string | null;
  /** @nullable */
  address2_postalcode?: string | null;
  /** @nullable */
  address2_stateorprovince?: string | null;
  /** @nullable */
  emailaddress1?: string | null;
  /** @nullable */
  fax?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  telephone1?: string | null;
  /** @nullable */
  readonly fortunecookietype?: string | null;
}
