/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsCAPApplicationContractPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @minLength 1 */
  vsd_contractid: string;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  vsd_authorizedsigningofficersignature?: string | null;
  /** @nullable */
  vsd_signingofficersname?: string | null;
  /** @nullable */
  vsd_signingofficertitle?: string | null;
  /**
   * @minimum 100000000
   * @maximum 100000001
   * @nullable
   */
  vsd_cpu_insuranceoptions?: number | null;
  /**
   * @minimum 100000000
   * @maximum 100000001
   * @nullable
   */
  vsd_collaborationwithkeystakeholders?: number | null;
  /**
   * @minimum 100000000
   * @maximum 100000001
   * @nullable
   */
  vsd_complaintandfeedbackprocessforparticipant?: number | null;
  vsd_criminalrecordchecks?: boolean;
  /**
   * @minimum 100000000
   * @maximum 100000001
   * @nullable
   */
  vsd_letterofreferencefromreferralsources?: number | null;
  /**
   * @minimum 100000000
   * @maximum 100000001
   * @nullable
   */
  vsd_establishedconfidentialityguidelines?: number | null;
}
