/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsCAPApplicationOrganizationPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  _ownerid_value?: string | null;
  /** @minLength 1 */
  accountid: string;
  /** @nullable */
  name?: string | null;
  /** @minLength 1 */
  address1_line1: string;
  /** @nullable */
  address1_line2?: string | null;
  /** @minLength 1 */
  address1_city: string;
  /** @minLength 1 */
  address1_postalcode: string;
  /** @nullable */
  address1_stateorprovince?: string | null;
  /** @nullable */
  address1_country?: string | null;
  /** @nullable */
  address1_composite?: string | null;
}
