/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsProgramApplicationContractPost {
  /** @nullable */
  vsd_ContactLookup1fortunecookiebind?: string | null;
  /** @nullable */
  vsd_ContactLookup2fortunecookiebind?: string | null;
  /** @nullable */
  vsd_cpu_subcontractedprogramstaff?: number | null;
  /** @nullable */
  vsd_cpu_unionizedstaff?: number | null;
  /** @nullable */
  vsd_cpu_insuranceoptions?: number | null;
  /** @nullable */
  vsd_cpu_memberofcssea?: number | null;
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_contractid?: string | null;
  /** @nullable */
  vsd_cpu_humanresourcepolices?: string | null;
  /** @nullable */
  vsd_cpu_specificunion?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  vsd_authorizedsigningofficersignature?: string | null;
  /** @nullable */
  vsd_signingofficersname?: string | null;
  /** @nullable */
  vsd_signingofficertitle?: string | null;
}
