/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsScheduleGLineItemCollectionPost {
  vsd_actualexpensescurrentquarter?: number;
  vsd_quarterlyvariance?: number;
  vsd_actualexpendituresyeartodate?: number;
  vsd_yeartodatevariance?: number;
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_scheduleglineitemid?: string | null;
  /** @nullable */
  vsd_explanationforvariance?: string | null;
}
