/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsDocumentPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  filename?: string | null;
  /** @nullable */
  subject?: string | null;
}
