/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsBudgetProposalProgramPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_programid?: string | null;
  /** @nullable */
  vsd_signingofficersignature?: string | null;
  /** @nullable */
  vsd_signingofficerfullname?: string | null;
  /** @nullable */
  vsd_signingofficertitle?: string | null;
}
