/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsBudgetProposalRevenueSourcePost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_programrevenuesourceid?: string | null;
  /** @nullable */
  vsd_cpu_otherrevenuesource?: string | null;
  vsd_cpu_revenuesourcetype?: number;
  /** @nullable */
  vsd_cashcontribution?: number | null;
  /** @nullable */
  vsd_inkindcontribution?: number | null;
  /** @nullable */
  statecode?: number | null;
  /** @nullable */
  vsd_ProgramIdfortunecookiebind?: string | null;
}
