/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsProgramSurplus {
  /** @minLength 1 */
  vsd_surplusplanreportid: string;
  vsd_surplusremittance?: boolean;
  /** @nullable */
  vsd_datesubmitted?: string | null;
  /** @nullable */
  readonly fortunecookietype?: string | null;
}
