/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsBudgetProposalExpensePost {
  /** @nullable */
  vsd_cpu_titleposition?: string | null;
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_programexpenseid?: string | null;
  vsd_cpu_programexpensetype?: number;
  /** @nullable */
  vsd_cpu_otherexpense?: string | null;
  vsd_totalcost?: number;
  vsd_inputamount?: number;
  vsd_cpu_salary?: number;
  vsd_cpu_fundedfromvscp?: number;
  vsd_cpu_benefits?: number;
  /** @nullable */
  statecode?: number | null;
  /** @nullable */
  vsd_EligibleExpenseItemIdfortunecookiebind?: string | null;
  /** @nullable */
  vsd_ProgramIdfortunecookiebind?: string | null;
}
