/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsProgramApplicationSchedulePost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_days?: string | null;
  /** @nullable */
  vsd_scheduledendtime?: string | null;
  /** @nullable */
  vsd_scheduledstarttime?: string | null;
  /** @nullable */
  vsd_scheduleid?: string | null;
  vsd_cpu_scheduletype?: number;
  /**
   * @minimum 0
   * @maximum 1
   * @nullable
   */
  statecode?: number | null;
  /** @minLength 1 */
  vsd_ProgramIdfortunecookiebind: string;
}
