/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsProgramApplicationProgramContactPost {
  /** @nullable */
  contactid?: string | null;
  /** @nullable */
  vsd_programid?: string | null;
  /** @nullable */
  readonly fortunecookietype?: string | null;
}
