/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsBudgetProposalExpensePost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_programexpenseid?: string | null;
  /**
   * @minimum 100000000
   * @maximum 100000002
   */
  vsd_cpu_programexpensetype?: number;
  /** @nullable */
  vsd_cpu_otherexpense?: string | null;
  /** @nullable */
  vsd_cpu_titleposition?: string | null;
  /**
   * @minimum 0
   * @maximum 10000000
   */
  vsd_totalcost?: number;
  /**
   * @minimum 0
   * @maximum 10000000
   */
  vsd_inputamount?: number;
  /**
   * @minimum 0
   * @maximum 10000000
   */
  vsd_cpu_salary?: number;
  /**
   * @minimum 0
   * @maximum 10000000
   */
  vsd_cpu_fundedfromvscp?: number;
  /**
   * @minimum 0
   * @maximum 10000000
   */
  vsd_cpu_benefits?: number;
  /**
   * @minimum 0
   * @maximum 1
   * @nullable
   */
  statecode?: number | null;
  /** @nullable */
  vsd_EligibleExpenseItemIdfortunecookiebind?: string | null;
  /** @minLength 1 */
  vsd_ProgramIdfortunecookiebind: string;
}
