/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsProgramSurplusLineItemPost {
  /** @nullable */
  vsd_justificationdetails?: string | null;
  /**
   * @minimum 0
   * @maximum 10000000
   * @nullable
   */
  vsd_actualexpenditures?: number | null;
  /**
   * @minimum 0
   * @maximum 10000000
   * @nullable
   */
  vsd_actualexpenditures2?: number | null;
  /**
   * @minimum 0
   * @maximum 10000000
   * @nullable
   */
  vsd_actualexpenditures3?: number | null;
  /**
   * @minimum 0
   * @maximum 10000000
   * @nullable
   */
  vsd_actualexpenditures4?: number | null;
  /**
   * @minimum 0
   * @maximum 10000000
   * @nullable
   */
  vsd_allocatedamount?: number | null;
  /**
   * @minimum 0
   * @maximum 10000000
   * @nullable
   */
  vsd_proposedexpenditures?: number | null;
  /** @minLength 1 */
  vsd_surpluslineitemid: string;
  /** @nullable */
  vsd_datesubmitted?: string | null;
  /** @nullable */
  readonly fortunecookietype?: string | null;
}
