/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsOrganizationContactPost {
  /** @nullable */
  _parentcustomerid_value?: string | null;
  /** @nullable */
  address1_city?: string | null;
  /** @nullable */
  address1_composite?: string | null;
  /** @nullable */
  address1_line1?: string | null;
  /** @nullable */
  address1_line2?: string | null;
  /** @nullable */
  address1_postalcode?: string | null;
  /** @nullable */
  address1_stateorprovince?: string | null;
  /** @nullable */
  contactid?: string | null;
  /** @minLength 1 */
  emailaddress1: string;
  /** @nullable */
  fax?: string | null;
  /** @minLength 1 */
  firstname: string;
  /** @nullable */
  fullname?: string | null;
  /** @nullable */
  jobtitle?: string | null;
  /** @minLength 1 */
  lastname: string;
  /** @nullable */
  middlename?: string | null;
  /** @nullable */
  mobilephone?: string | null;
  /** @nullable */
  vsd_mainphoneextension?: string | null;
  /** @nullable */
  telephone2?: string | null;
  /** @nullable */
  vsd_homephoneextension?: string | null;
  /**
   * @minimum 100000000
   * @maximum 100000004
   * @nullable
   */
  vsd_employmentstatus?: number | null;
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_bceid?: string | null;
  /**
   * @minimum 0
   * @maximum 1
   * @nullable
   */
  statecode?: number | null;
}
