/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsSignaturePost {
  /** @nullable */
  vsd_authorizedsigningofficersignature?: string | null;
  /** @nullable */
  vsd_signingofficersname?: string | null;
  /** @nullable */
  vsd_signingofficertitle?: string | null;
}
