/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsScheduleGLineItemCollectionPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @minLength 1 */
  vsd_scheduleglineitemid: string;
  /**
   * @minimum 0
   * @maximum 10000000
   */
  vsd_actualexpensescurrentquarter?: number;
  vsd_quarterlyvariance?: number;
  /**
   * @minimum 0
   * @maximum 10000000
   */
  vsd_actualexpendituresyeartodate?: number;
  vsd_yeartodatevariance?: number;
  /** @nullable */
  vsd_explanationforvariance?: string | null;
}
