/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsDataCollectionLineItemPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  _vsd_questionid_value?: string | null;
  /** @nullable */
  vsd_questioncategory?: string | null;
  /** @nullable */
  vsd_number?: number | null;
  vsd_questiontype1?: number;
  vsd_questionorder?: number;
  /** @nullable */
  vsd_textanswer?: string | null;
  /** @nullable */
  vsd_yesno?: number | null;
  /** @nullable */
  vsd_QuestionIdfortunecookiebind?: string | null;
  /** @nullable */
  vsd_CategoryIdfortunecookiebind?: string | null;
}
