/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsBudgetProposalRevenueSourcePost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_programrevenuesourceid?: string | null;
  /** @nullable */
  vsd_cpu_otherrevenuesource?: string | null;
  /**
   * @minimum 100000000
   * @maximum 100000004
   */
  vsd_cpu_revenuesourcetype?: number;
  /**
   * @minimum 0
   * @maximum 10000000
   * @nullable
   */
  vsd_cashcontribution?: number | null;
  /**
   * @minimum 0
   * @maximum 10000000
   * @nullable
   */
  vsd_inkindcontribution?: number | null;
  /**
   * @minimum 0
   * @maximum 1
   * @nullable
   */
  statecode?: number | null;
  /** @minLength 1 */
  vsd_ProgramIdfortunecookiebind: string;
}
