/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsRegisterNewUserContactPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @minLength 1 */
  address1_city: string;
  /** @nullable */
  address1_composite?: string | null;
  /** @minLength 1 */
  address1_line1: string;
  /** @nullable */
  address1_line2?: string | null;
  /** @minLength 1 */
  address1_postalcode: string;
  /** @nullable */
  address1_stateorprovince?: string | null;
  /** @minLength 1 */
  emailaddress1: string;
  /** @nullable */
  fax?: string | null;
  /** @minLength 1 */
  firstname: string;
  /** @nullable */
  fullname?: string | null;
  /**
   * @minimum 100000000
   * @maximum 2147483647
   */
  vsd_contactrole?: number;
  /** @minLength 1 */
  jobtitle: string;
  /** @minLength 1 */
  lastname: string;
  /** @nullable */
  middlename?: string | null;
  /** @minLength 1 */
  mobilephone: string;
  /** @nullable */
  vsd_mainphoneextension?: string | null;
  /** @nullable */
  telephone2?: string | null;
  /** @nullable */
  vsd_homephoneextension?: string | null;
}
