/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsCAPApplicationContractPost {
  /** @nullable */
  vsd_cpu_insuranceoptions?: number | null;
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_contractid?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  vsd_authorizedsigningofficersignature?: string | null;
  /** @nullable */
  vsd_signingofficersname?: string | null;
  /** @nullable */
  vsd_signingofficertitle?: string | null;
  /** @nullable */
  vsd_collaborationwithkeystakeholders?: number | null;
  /** @nullable */
  vsd_complaintandfeedbackprocessforparticipant?: number | null;
  vsd_criminalrecordchecks?: boolean;
  /** @nullable */
  vsd_letterofreferencefromreferralsources?: number | null;
  /** @nullable */
  vsd_establishedconfidentialityguidelines?: number | null;
}
