/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsProgramApplicationProgramContactPost {
  /** @minLength 1 */
  contactid: string;
  /** @minLength 1 */
  vsd_programid: string;
  /** @nullable */
  readonly fortunecookietype?: string | null;
}
