/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsRegisterNewUserServiceProviderPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  address1_city: string;
  /** @nullable */
  address1_composite?: string | null;
  /** @minLength 1 */
  address1_line1: string;
  /** @nullable */
  address1_line2?: string | null;
  /** @minLength 1 */
  address1_postalcode: string;
  /** @nullable */
  address1_stateorprovince?: string | null;
  /** @minLength 1 */
  emailaddress1: string;
  /** @nullable */
  fax?: string | null;
  /** @minLength 1 */
  telephone1: string;
}
