/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsCAPApplicationProgramPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_programid?: string | null;
  vsd_cpu_fundingamountrequested?: number;
  /** @nullable */
  vsd_cpu_programmodeltypes?: string | null;
  /** @nullable */
  vsd_otherprogrammodels?: string | null;
  vsd_cpu_programevaluationefforts?: number;
  /** @nullable */
  vsd_cpu_programevaluationdescription?: string | null;
  /** @nullable */
  vsd_cpu_capprogramoperationscomments?: string | null;
  /** @nullable */
  vsd_ContactLookupfortunecookiebind?: string | null;
}
