/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsRegisterNewUserServiceProviderPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  address1_city?: string | null;
  /** @nullable */
  address1_composite?: string | null;
  /** @nullable */
  address1_line1?: string | null;
  /** @nullable */
  address1_line2?: string | null;
  /** @nullable */
  address1_postalcode?: string | null;
  /** @nullable */
  address1_stateorprovince?: string | null;
  /** @nullable */
  emailaddress1?: string | null;
  /** @nullable */
  fax?: string | null;
  /** @nullable */
  telephone1?: string | null;
}
