/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface DynamicsProgramApplicationProgramPost {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  vsd_costshare?: boolean;
  vsd_cpu_programstaffsubcontracted?: boolean;
  /** @nullable */
  vsd_cpu_per?: number | null;
  /** @nullable */
  vsd_totaloncallstandbyhours?: number | null;
  /** @nullable */
  vsd_totalscheduledhours?: number | null;
  /** @nullable */
  vsd_addressline1?: string | null;
  /** @nullable */
  vsd_addressline2?: string | null;
  /** @nullable */
  vsd_city?: string | null;
  /** @nullable */
  vsd_country?: string | null;
  /** @nullable */
  vsd_emailaddress?: string | null;
  /** @nullable */
  vsd_fax?: string | null;
  /** @nullable */
  vsd_governmentfunderagency?: string | null;
  /** @nullable */
  vsd_mailingaddressline1?: string | null;
  /** @nullable */
  vsd_mailingaddressline2?: string | null;
  /** @nullable */
  vsd_mailingcity?: string | null;
  /** @nullable */
  vsd_mailingcountry?: string | null;
  /** @nullable */
  vsd_mailingpostalcodezip?: string | null;
  /** @nullable */
  vsd_mailingprovincestate?: string | null;
  /** @nullable */
  vsd_phonenumber?: string | null;
  /** @nullable */
  vsd_postalcodezip?: string | null;
  /** @nullable */
  vsd_programid?: string | null;
  /** @nullable */
  vsd_provincestate?: string | null;
  vsd_addresstransitionorsafehome?: boolean;
  /** @nullable */
  vsd_ContactLookupfortunecookiebind?: string | null;
  /** @nullable */
  vsd_ContactLookup2fortunecookiebind?: string | null;
  /** @nullable */
  vsd_ContactLookup3fortunecookiebind?: string | null;
}
