/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsScheduleGCollectionPost } from './dynamicsScheduleGCollectionPost';
import type { DynamicsScheduleGLineItemCollectionPost } from './dynamicsScheduleGLineItemCollectionPost';

export interface ExpenseReportPost {
  /** @nullable */
  businessBCeID?: string | null;
  /** @nullable */
  userBCeID?: string | null;
  /** @nullable */
  scheduleGCollection?: DynamicsScheduleGCollectionPost[] | null;
  /** @nullable */
  scheduleGLineItemCollection?: DynamicsScheduleGLineItemCollectionPost[] | null;
}
