/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { ContractDto } from './contractDto';
import type { OrganizationDto } from './organizationDto';
import type { PortalRoleDto } from './portalRoleDto';
import type { ProgramDto } from './programDto';
import type { ScheduleGDto } from './scheduleGDto';
import type { ScheduleGLineItemDto } from './scheduleGLineItemDto';

export interface ExpenseReportDto {
  isSuccess?: boolean;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  businessbceid?: string | null;
  /** @nullable */
  userbceid?: string | null;
  contract?: ContractDto;
  organization?: OrganizationDto;
  /** @nullable */
  portalRoles?: PortalRoleDto[] | null;
  program?: ProgramDto;
  scheduleG?: ScheduleGDto;
  /** @nullable */
  scheduleGLineItems?: ScheduleGLineItemDto[] | null;
}
