/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsScheduleGCollectionPost } from './dynamicsScheduleGCollectionPost';
import type { DynamicsScheduleGLineItemCollectionPost } from './dynamicsScheduleGLineItemCollectionPost';

export interface ExpenseReportPost {
  /** @minLength 1 */
  businessBCeID: string;
  /** @minLength 1 */
  userBCeID: string;
  /** @minItems 1 */
  scheduleGCollection: DynamicsScheduleGCollectionPost[];
  scheduleGLineItemCollection: DynamicsScheduleGLineItemCollectionPost[];
}
