/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsDocumentPost } from './dynamicsDocumentPost';

export interface FilePost {
  /** @nullable */
  businessBCeID?: string | null;
  /** @nullable */
  userBCeID?: string | null;
  /** @nullable */
  documentCollection?: DynamicsDocumentPost[] | null;
}
