/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface MessageDto {
  /** @nullable */
  regardingObjectId?: string | null;
  /** @nullable */
  vsd_Program?: string | null;
  /** @nullable */
  vsd_Cpu_RegionDistrict?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
