/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DataCollectionItemDto } from './dataCollectionItemDto';
import type { ContactMinimalDto } from './contactMinimalDto';
import type { ProgramMinimalDto } from './programMinimalDto';

export interface MonthlyStatisticsDto {
  isSuccess?: boolean;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  businessbceid?: string | null;
  /** @nullable */
  userbceid?: string | null;
  /** @nullable */
  dataCollection?: DataCollectionItemDto[] | null;
  /** @nullable */
  contactCollection?: ContactMinimalDto[] | null;
  /** @nullable */
  programCollection?: ProgramMinimalDto[] | null;
}
