/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsDataCollectionLineItemPost } from './dynamicsDataCollectionLineItemPost';

export interface MonthlyStatisticsAnswers {
  /** @nullable */
  businessBCeID?: string | null;
  /** @nullable */
  userBCeID?: string | null;
  /** @nullable */
  statusCode?: number | null;
  /** @nullable */
  answerCollection?: DynamicsDataCollectionLineItemPost[] | null;
}
