/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsDataCollectionLineItemPost } from './dynamicsDataCollectionLineItemPost';

export interface MonthlyStatisticsAnswers {
  /** @minLength 1 */
  businessBCeID: string;
  /** @minLength 1 */
  userBCeID: string;
  /** @nullable */
  statusCode?: number | null;
  /** @nullable */
  answerCollection?: DynamicsDataCollectionLineItemPost[] | null;
}
