/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsOrganizationPost } from './dynamicsOrganizationPost';
import type { DynamicsOrganizationContactPost } from './dynamicsOrganizationContactPost';

export interface OrganizationPost {
  /** @minLength 1 */
  businessBCeID: string;
  /** @minLength 1 */
  userBCeID: string;
  organization?: DynamicsOrganizationPost;
  /** @nullable */
  staffCollection?: DynamicsOrganizationContactPost[] | null;
}
