/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface OrganizationDto {
  /** @nullable */
  accountId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  telephone1?: string | null;
  /** @nullable */
  emailAddress1?: string | null;
  /** @nullable */
  fax?: string | null;
  /** @nullable */
  address1City?: string | null;
  /** @nullable */
  address1Line1?: string | null;
  /** @nullable */
  address1Line2?: string | null;
  /** @nullable */
  address1PostalCode?: string | null;
  /** @nullable */
  address1StateOrProvince?: string | null;
  /** @nullable */
  address1Country?: string | null;
  /** @nullable */
  address2City?: string | null;
  /** @nullable */
  address2Line1?: string | null;
  /** @nullable */
  address2Line2?: string | null;
  /** @nullable */
  address2PostalCode?: string | null;
  /** @nullable */
  address2StateOrProvince?: string | null;
  /** @nullable */
  address2Country?: string | null;
  /** @nullable */
  executiveContactIdValue?: string | null;
  /** @nullable */
  boardContactIdValue?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
