/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface ProgramDto {
  /** @nullable */
  vsd_ProgramId?: string | null;
  /** @nullable */
  vsd_Name?: string | null;
  /** @nullable */
  vsd_ContractIdValue?: string | null;
  /** @nullable */
  vsd_ContactLookupValue?: string | null;
  /** @nullable */
  vsd_City?: string | null;
  /** @nullable */
  vsd_AddressLine1?: string | null;
  /** @nullable */
  vsd_AddressLine2?: string | null;
  /** @nullable */
  vsd_ProvinceState?: string | null;
  /** @nullable */
  vsd_EmailAddress?: string | null;
  /** @nullable */
  vsd_Fax?: string | null;
  /** @nullable */
  vsd_MailingCity?: string | null;
  /** @nullable */
  vsd_MailingAddressLine1?: string | null;
  /** @nullable */
  vsd_MailingAddressLine2?: string | null;
  /** @nullable */
  vsd_MailingProvinceState?: string | null;
  /** @nullable */
  vsd_PhoneNumber?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
