/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsProgramSurplusLineItemPost } from './dynamicsProgramSurplusLineItemPost';
import type { DynamicsProgramSurplus } from './dynamicsProgramSurplus';

export interface ProgramSurplusPost {
  /** @minLength 1 */
  businessBCeID: string;
  /** @minLength 1 */
  userBCeID: string;
  /** @nullable */
  surplusPlanLineItemCollection?: DynamicsProgramSurplusLineItemPost[] | null;
  /** @minItems 1 */
  surplusPlanCollection: DynamicsProgramSurplus[];
}
