/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsProgramApplicationProgramContactPost } from './dynamicsProgramApplicationProgramContactPost';
import type { DynamicsProgramApplicationOrganizationPost } from './dynamicsProgramApplicationOrganizationPost';
import type { DynamicsProgramApplicationContractPost } from './dynamicsProgramApplicationContractPost';
import type { DynamicsProgramApplicationContactPost } from './dynamicsProgramApplicationContactPost';
import type { DynamicsProgramApplicationSchedulePost } from './dynamicsProgramApplicationSchedulePost';
import type { DynamicsProgramApplicationProgramPost } from './dynamicsProgramApplicationProgramPost';

export interface ProgramApplicationPost {
  /** @nullable */
  businessBCeID?: string | null;
  /** @nullable */
  userBCeID?: string | null;
  /** @nullable */
  addProgramContactCollection?: DynamicsProgramApplicationProgramContactPost[] | null;
  /** @nullable */
  removeProgramContactCollection?: DynamicsProgramApplicationProgramContactPost[] | null;
  /** @nullable */
  addProgramSubContractorCollection?: DynamicsProgramApplicationProgramContactPost[] | null;
  /** @nullable */
  removeProgramSubContractorCollection?: DynamicsProgramApplicationProgramContactPost[] | null;
  organization?: DynamicsProgramApplicationOrganizationPost;
  /** @nullable */
  contractCollection?: DynamicsProgramApplicationContractPost[] | null;
  /** @nullable */
  contactCollection?: DynamicsProgramApplicationContactPost[] | null;
  /** @nullable */
  scheduleCollection?: DynamicsProgramApplicationSchedulePost[] | null;
  /** @nullable */
  programCollection?: DynamicsProgramApplicationProgramPost[] | null;
}
