/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface ProgramDto {
  /** @nullable */
  vsd_ProgramId?: string | null;
  /** @nullable */
  vsd_Name?: string | null;
  /** @nullable */
  vsd_ContractIdValue?: string | null;
  /** @nullable */
  vsd_ContactLookupValue?: string | null;
  /** @nullable */
  vsd_ContactLookup2Value?: string | null;
  /** @nullable */
  vsd_ContactLookup3Value?: string | null;
  /** @nullable */
  vsd_AddressLine1?: string | null;
  /** @nullable */
  vsd_AddressLine2?: string | null;
  /** @nullable */
  vsd_City?: string | null;
  /** @nullable */
  vsd_PostalCodeZip?: string | null;
  /** @nullable */
  vsd_ProvinceState?: string | null;
  /** @nullable */
  vsd_Country?: string | null;
  /** @nullable */
  vsd_MailingAddressLine1?: string | null;
  /** @nullable */
  vsd_MailingAddressLine2?: string | null;
  /** @nullable */
  vsd_MailingCity?: string | null;
  /** @nullable */
  vsd_MailingPostalCodeZip?: string | null;
  /** @nullable */
  vsd_MailingProvinceState?: string | null;
  /** @nullable */
  vsd_MailingCountry?: string | null;
  /** @nullable */
  vsd_EmailAddress?: string | null;
  /** @nullable */
  vsd_Fax?: string | null;
  /** @nullable */
  vsd_PhoneNumber?: string | null;
  /** @nullable */
  vsd_GovernmentFunderAgency?: string | null;
  /** @nullable */
  vsd_CostShare?: boolean | null;
  /** @nullable */
  vsd_AddressTransitionOrSafeHome?: boolean | null;
  /** @nullable */
  vsd_Cpu_ProgramStaffSubcontracted?: boolean | null;
  /** @nullable */
  vsd_Cpu_Per?: number | null;
  /** @nullable */
  vsd_Cpu_NumberOfHours?: number | null;
  /** @nullable */
  vsd_TotalScheduledHours?: number | null;
  /** @nullable */
  vsd_TotalOnCallStandbyHours?: number | null;
  /** @nullable */
  vsd_Cpu_CapProgramOperationsComments?: string | null;
  /** @nullable */
  vsd_Cpu_FoundingAmountRequested?: number | null;
  /** @nullable */
  vsd_Cpu_EstimatedSubtotalComponentValue?: number | null;
  /** @nullable */
  vsd_ProgramTypeValue?: string | null;
  /** @nullable */
  vsd_Cpu_RegionDistrictValue?: string | null;
  /** @nullable */
  vsd_Cpu_Program_Location?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
  /** @nullable */
  vsd_Cpu_ProgramModelTypes?: string | null;
}
