/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsProgramSurplusLineItemPost } from './dynamicsProgramSurplusLineItemPost';
import type { DynamicsProgramSurplus } from './dynamicsProgramSurplus';

export interface ProgramSurplusPost {
  /** @nullable */
  businessBCeID?: string | null;
  /** @nullable */
  userBCeID?: string | null;
  /** @nullable */
  surplusPlanLineItemCollection?: DynamicsProgramSurplusLineItemPost[] | null;
  /** @nullable */
  surplusPlanCollection?: DynamicsProgramSurplus[] | null;
}
