/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { ContactDto } from './contactDto';
import type { ContractDto } from './contractDto';
import type { OrganizationDto } from './organizationDto';
import type { PortalRoleDto } from './portalRoleDto';
import type { ProgramDto } from './programDto';
import type { ProgramContactDto } from './programContactDto';
import type { ProgramTypeDto } from './programTypeDto';
import type { RegionDistrictDto } from './regionDistrictDto';
import type { ScheduleDto } from './scheduleDto';
import type { ServiceAreaDto } from './serviceAreaDto';

export interface ProgramApplicationDto {
  boardContact?: ContactDto;
  /** @nullable */
  businessbceid?: string | null;
  contract?: ContractDto;
  executiveContact?: ContactDto;
  isSuccess?: boolean;
  organization?: OrganizationDto;
  /** @nullable */
  portalRoles?: PortalRoleDto[] | null;
  /** @nullable */
  programCollection?: ProgramDto[] | null;
  /** @nullable */
  programContactCollection?: ProgramContactDto[] | null;
  /** @nullable */
  programSubcontractorCollection?: ProgramContactDto[] | null;
  /** @nullable */
  programTypeCollection?: ProgramTypeDto[] | null;
  /** @nullable */
  regionDistrictCollection?: RegionDistrictDto[] | null;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  scheduleCollection?: ScheduleDto[] | null;
  /** @nullable */
  serviceAreaCollection?: ServiceAreaDto[] | null;
  /** @nullable */
  staffCollection?: ContactDto[] | null;
  /** @nullable */
  userbceid?: string | null;
}
