/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsRegisterNewUserContactPost } from './dynamicsRegisterNewUserContactPost';
import type { DynamicsRegisterNewUserServiceProviderPost } from './dynamicsRegisterNewUserServiceProviderPost';

export interface RegisterNewUserPost {
  /** @nullable */
  businessBCeID?: string | null;
  /** @nullable */
  userBCeID?: string | null;
  newContact?: DynamicsRegisterNewUserContactPost;
  newServiceProvider?: DynamicsRegisterNewUserServiceProviderPost;
}
