/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { DynamicsRegisterNewUserContactPost } from './dynamicsRegisterNewUserContactPost';
import type { DynamicsRegisterNewUserServiceProviderPost } from './dynamicsRegisterNewUserServiceProviderPost';

export interface RegisterNewUserPost {
  /** @minLength 1 */
  businessBCeID: string;
  /** @minLength 1 */
  userBCeID: string;
  newContact: DynamicsRegisterNewUserContactPost;
  newServiceProvider?: DynamicsRegisterNewUserServiceProviderPost;
}
