/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface ScheduleGDto {
  /** @nullable */
  vsd_ScheduleGId?: string | null;
  /** @nullable */
  vsd_ActualHoursThisQuarter?: number | null;
  /** @nullable */
  vsd_ContractedServiceHrsThisQuarter?: number | null;
  /** @nullable */
  vsd_ProgramAdministrationCurrentQuarter?: number | null;
  /** @nullable */
  vsd_QuarterlyVarianceProgramAdministration?: number | null;
  /** @nullable */
  vsd_YearToDateProgramAdministration?: number | null;
  /** @nullable */
  vsd_YearToDateVarianceProgramAdministration?: number | null;
  /** @nullable */
  vsd_ProgramDeliveryCurrentQuarter?: number | null;
  /** @nullable */
  vsd_QuarterlyVarianceProgramDelivery?: number | null;
  /** @nullable */
  vsd_YearToDateProgramDelivery?: number | null;
  /** @nullable */
  vsd_YearToDateVarianceProgramDelivery?: number | null;
  /** @nullable */
  vsd_SalariesBenefitsCurrentQuarter?: number | null;
  /** @nullable */
  vsd_QuarterlyVarianceSalariesBenefits?: number | null;
  /** @nullable */
  vsd_YearToDateSalariesAndBenefits?: number | null;
  /** @nullable */
  vsd_YearToDateVarianceSalariesBenefits?: number | null;
  /** @nullable */
  vsd_SalaryAndBenefitsBudgeted?: number | null;
  /** @nullable */
  vsd_QuarterlyBudgetedSalariesBenefits?: number | null;
  /** @nullable */
  vsd_ProgramDeliveryBudgeted?: number | null;
  /** @nullable */
  vsd_QuarterlyBudgetedProgramDelivery?: number | null;
  /** @nullable */
  vsd_ProgramAdministrationBudgeted?: number | null;
  /** @nullable */
  vsd_QuarterlyBudgetedProgramAdministration?: number | null;
  /** @nullable */
  vsd_Cpu_ReportingPeriod?: number | null;
  /** @nullable */
  vsd_ProgramAdministrationExplanation?: string | null;
  /** @nullable */
  vsd_ProgramDeliveryExplanations?: string | null;
  /** @nullable */
  vsd_SalariesAndBenefitsExplanation?: string | null;
  /** @nullable */
  vsd_ReportReviewed?: boolean | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
