/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface ScheduleGLineItemDto {
  /** @nullable */
  vsd_ScheduleGLineItemId?: string | null;
  /** @nullable */
  vsd_ExpenseLineItemValue?: string | null;
  /** @nullable */
  vsd_ScheduleGIdValue?: string | null;
  /** @nullable */
  vsd_AnnualBudgetedAmount?: number | null;
  /** @nullable */
  vsd_QuarterlyBudgetedAmount?: number | null;
  /** @nullable */
  vsd_ActualExpensesCurrentQuarter?: number | null;
  /** @nullable */
  vsd_QuarterlyVariance?: number | null;
  /** @nullable */
  vsd_ActualExpendituresYearToDate?: number | null;
  /** @nullable */
  vsd_YearToDateVariance?: number | null;
  /** @nullable */
  vsd_ExplanationForVariance?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
