/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface ScheduleDto {
  /** @nullable */
  vsd_ScheduleId?: string | null;
  /** @nullable */
  vsd_Days?: number[] | null;
  /** @nullable */
  vsd_ScheduledStartTime?: string | null;
  /** @nullable */
  vsd_ScheduledEndTime?: string | null;
  /** @nullable */
  vsd_Cpu_ScheduleType?: number | null;
  /** @nullable */
  stateCode?: number | null;
  /** @nullable */
  vsd_ProgramIdValue?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
