/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface ServiceAreaDto {
  /** @nullable */
  vsd_ServiceAreaId?: string | null;
  /** @nullable */
  vsd_Name?: string | null;
  /** @nullable */
  vsd_ProgramId?: string | null;
  /** @nullable */
  vsd_RegionDistrictId?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
