/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface StatusReportProgramDto {
  /** @nullable */
  vsd_programid?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  _vsd_contractid_value?: string | null;
  /** @nullable */
  _vsd_programtype_value?: string | null;
  /** @nullable */
  _vsd_serviceproviderid_value?: string | null;
  /** @nullable */
  vsd_cpu_numberofhours?: number | null;
}
