/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface StatusReportCategoryDto {
  /** @nullable */
  vsd_monthlystatisticscategoryid?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  vsd_categoryorder?: number | null;
}
