/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { StatusReportContractDto } from './statusReportContractDto';
import type { StatusReportProgramDto } from './statusReportProgramDto';
import type { StatusReportOrganizationDto } from './statusReportOrganizationDto';
import type { StatusReportCategoryDto } from './statusReportCategoryDto';
import type { StatusReportQuestionItemDto } from './statusReportQuestionItemDto';
import type { StatusReportMcQuestionDto } from './statusReportMcQuestionDto';
import type { StatusReportProgramTypeDto } from './statusReportProgramTypeDto';
import type { StatusReportChildQuestionDto } from './statusReportChildQuestionDto';
import type { StatusReportChildMcQuestionDto } from './statusReportChildMcQuestionDto';
import type { StatusReportAnswerItemDto } from './statusReportAnswerItemDto';

export interface StatusReportQuestionsDto {
  isSuccess?: boolean;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  businessbceid?: string | null;
  /** @nullable */
  userbceid?: string | null;
  /** @nullable */
  reportingPeriod?: number | null;
  /** @nullable */
  dataCollectionid?: string | null;
  contract?: StatusReportContractDto;
  program?: StatusReportProgramDto;
  organization?: StatusReportOrganizationDto;
  /** @nullable */
  categoryCollection?: StatusReportCategoryDto[] | null;
  /** @nullable */
  questionCollection?: StatusReportQuestionItemDto[] | null;
  /** @nullable */
  multipleChoiceCollection?: StatusReportMcQuestionDto[] | null;
  /** @nullable */
  programTypeCollection?: StatusReportProgramTypeDto[] | null;
  /** @nullable */
  childQuestionCollection?: StatusReportChildQuestionDto[] | null;
  /** @nullable */
  childMultipleChoiceCollection?: StatusReportChildMcQuestionDto[] | null;
  /** @nullable */
  answerCollection?: StatusReportAnswerItemDto[] | null;
}
