/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */
import type { StatusReportAnswerItemDto } from './statusReportAnswerItemDto';
import type { StatusReportCategoryDto } from './statusReportCategoryDto';
import type { StatusReportContactDto } from './statusReportContactDto';
import type { StatusReportContractDto } from './statusReportContractDto';
import type { StatusReportOrganizationDto } from './statusReportOrganizationDto';
import type { StatusReportProgramDto } from './statusReportProgramDto';

export interface StatusReportAnswersDto {
  isSuccess?: boolean;
  /** @nullable */
  result?: string | null;
  /** @nullable */
  businessbceid?: string | null;
  /** @nullable */
  userbceid?: string | null;
  /** @nullable */
  reportingPeriod?: number | null;
  /** @nullable */
  answerCollection?: StatusReportAnswerItemDto[] | null;
  /** @nullable */
  categoryCollection?: StatusReportCategoryDto[] | null;
  contact?: StatusReportContactDto;
  contract?: StatusReportContractDto;
  organization?: StatusReportOrganizationDto;
  program?: StatusReportProgramDto;
}
