/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface StatusReportAnswerItemDto {
  /** @nullable */
  vsd_datacollectionlineitemid?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  _vsd_datacollectionid_value?: string | null;
  /** @nullable */
  vsd_questioncategory?: string | null;
  /** @nullable */
  vsd_questionorder?: number | null;
  /** @nullable */
  vsd_questiontype1?: number | null;
  /** @nullable */
  vsd_tooltip?: string | null;
  /** @nullable */
  vsd_yesno?: number | null;
  /** @nullable */
  vsd_textanswer?: string | null;
  /** @nullable */
  vsd_number?: number | null;
  /** @nullable */
  createdon?: string | null;
}
