/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface StatusReportChildQuestionDto {
  /** @nullable */
  vsd_cpustatisticsmasterdataid?: string | null;
  /** @nullable */
  _vsd_categoryid_value?: string | null;
  /** @nullable */
  _vsd_parentid_value?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  vsd_questionorder?: number | null;
  /** @nullable */
  vsd_questiontype?: number | null;
  /** @nullable */
  vsd_tooltip?: string | null;
}
