/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface StatusReportContractDto {
  /** @nullable */
  vsd_contractid?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  _vsd_customer_value?: string | null;
}
