/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface StatusReportContactDto {
  /** @nullable */
  contactid?: string | null;
  /** @nullable */
  firstname?: string | null;
  /** @nullable */
  lastname?: string | null;
}
