/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface SurplusLineItemDto {
  /** @nullable */
  vsd_SurplusLineItemId?: string | null;
  /** @nullable */
  vsd_Name?: string | null;
  /** @nullable */
  vsd_JustificationDetails?: string | null;
  /** @nullable */
  vsd_ActualExpenditures?: number | null;
  /** @nullable */
  vsd_ActualExpenditures2?: number | null;
  /** @nullable */
  vsd_ActualExpenditures3?: number | null;
  /** @nullable */
  vsd_ActualExpenditures4?: number | null;
  /** @nullable */
  vsd_AllocatedAmount?: number | null;
  /** @nullable */
  vsd_ProposedExpenditures?: number | null;
  /** @nullable */
  vsd_DateSubmitted?: string | null;
  /** @nullable */
  vsd_EligibleExpenseItemIdValue?: string | null;
  /** @nullable */
  vsd_SurplusPlanIdValue?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
