/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface SurplusPlanDto {
  /** @nullable */
  vsd_SurplusPlanReportId?: string | null;
  /** @nullable */
  vsd_SurplusAmount?: number | null;
  /** @nullable */
  vsd_SurplusRemittance?: boolean | null;
  /** @nullable */
  vsd_DateSubmitted?: string | null;
  /** @nullable */
  vsd_ProgramIdValue?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
