/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CPU Portal API
 * API documentation for CPU Portal
 * OpenAPI spec version: v1
 */

export interface TaskDto {
  /** @nullable */
  activityId?: string | null;
  /** @nullable */
  regardingObjectIdValue?: string | null;
  /** @nullable */
  statusCode?: number | null;
  /** @nullable */
  stateCode?: number | null;
  /** @nullable */
  vsd_TaskTypeIdValue?: string | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  scheduledEnd?: string | null;
  /** @nullable */
  modifiedOn?: string | null;
  /** @nullable */
  vsd_ProgramIdValue?: string | null;
  /** @nullable */
  vsd_ScheduleGIdValue?: string | null;
  /** @nullable */
  vsd_SurplusPlanIdValue?: string | null;
  /** @nullable */
  fortuneCookieType?: string | null;
  /** @nullable */
  fortuneCookieEtag?: string | null;
}
